# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: da590e572a0bf419a0d1088ffacba83aa6598e47c93f5cb420ff75cb0901452e93fb6a45347c20015f5cd3127fff9763e43ae8d0ee71f060044eb9e2a6a06fdb

test:
  secret_key_base: e5083b1bd589d1ce3010231d725c60291434e41366f323028c02e350abba7c407cf478ceb6e4cb3c89d04063e443661182ab130836506aa64446b06f3ba355bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
